// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OCR
{
    [default_interface]
    runtimeclass ConfigPage : Microsoft.UI.Xaml.Controls.Page
    {
        ConfigPage();
        ConfigPage(Microsoft.UI.Xaml.Window window);
        Int32 MyProperty;
    }
}
