// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.
import "SharedItem.idl";
import "LanguageItem.idl";

namespace OCR
{
    [default_interface]
    runtimeclass ConfigPage : Microsoft.UI.Xaml.Controls.Page
    {
        ConfigPage();
        ConfigPage(Microsoft.UI.Xaml.Window window);
        SharedItem SharedItem { get; };
        Windows.Foundation.Collections.IObservableVector<LanguageItem> LanguageItems { get; };
    }
}
