// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OCR
{
	[default_interface]
	runtimeclass MicaPage : Microsoft.UI.Xaml.Controls.Page
	{
		MicaPage();
	    MicaPage(Microsoft.UI.Xaml.Window window);
		Int32 MyProperty;
	}
}
