// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OCR
{
    [default_interface]
    runtimeclass OCROverlay : Microsoft.UI.Xaml.Controls.Page
    {
        OCROverlay();
        Int32 MyProperty;
    }
}
