// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OCR
{
    [default_interface]
    runtimeclass OverlayPanel : Microsoft.UI.Xaml.Controls.SwapChainPanel
    {
        OverlayPanel();
        OverlayPanel(Microsoft.UI.Xaml.Window window);
        Int32 MyProperty;
        Double MainBorderThickness;
        Double MainBorderMargin;
    }
}
