namespace OCR
{
    runtimeclass SharedItem : [default] Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
		SharedItem();
		String PyHome;
		String SitePackages;
		Double Width;
        Double Height;
        Double X;
        Double Y;
	}
}