// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OCR
{
    [default_interface]
    runtimeclass OverlayPanel : Microsoft.UI.Xaml.Controls.SwapChainPanel
    {
        OverlayPanel();
        OverlayPanel(Microsoft.UI.Xaml.Window window);
        Int32 MyProperty;
        Int32 NWidth { get; };
        Int32 NHeight { get; };
        Int32 NXWindow { get; };
        Int32 NYWindow { get; };
        Microsoft.UI.Xaml.Controls.Canvas MainCanvas { get; };
        Double MainBorderThickness;
        Double MainBorderMargin;
        void CleanCanvas();
    }
}
